name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-2025-vs2026
    strategy:
      matrix:
        configuration: [Debug, Release]

    steps:
      - uses: actions/checkout@v7

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v3

      - name: Build
        run: msbuild Outpost2DLL.sln /p:Configuration=${{ matrix.configuration }} /p:Platform=Win32
